use_frameworks!

target 'PhotoBrowserKit_Example' do
  pod 'PhotoBrowserKit', :path => '../'

  target 'PhotoBrowserKit_Tests' do
    inherit! :search_paths
    pod 'Kingfisher','~> 3.1.0’
    
  end
end
